{
 "title": "Spring Boot - Gestor de Tareas",
 "tags": [
  "spring-boot",
  "prometheus",
  "loki"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "Requests por segundo",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"spring-boot\", uri!~\".*actuator.*\"}[1m])",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Tiempo promedio de respuesta (ms)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "milliseconds" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"spring-boot\"}[1m]) / rate(http_server_requests_seconds_count{job=\"spring-boot\"}[1m]) * 1000",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Uso de memoria JVM (MB)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "megabytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"spring-boot\", area=\"heap\"} / 1024 / 1024",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Uso de CPU (%)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"spring-boot\", application=\"gestor-app\"} * 100\n",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "Threads activos JVM",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"spring-boot\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Errores HTTP",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 26, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\\\"spring-boot\\\", status=~\\\"4..\\\"}[1m]))",
     "legendFormat": "Errores 4xx"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\\\"spring-boot\\\", status=~\\\"5..\\\"}[1m]))",
     "legendFormat": "Errores 5xx"
    }
   ]
  },
  {
   "title": "Tiempo promedio por endpoint (ms)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 26, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "milliseconds" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"spring-boot\"}[1m]) / rate(http_server_requests_seconds_count{job=\"spring-boot\"}[1m]) * 1000",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Logs de la aplicación (Loki)",
   "type": "logs",
   "gridPos": { "x": 0, "y": 24, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "{service=\"gestor-app\"}"
    }
   ]
  }
 ]
}